# See full list of defaults here: https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# To see all cops used see here: https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  DisplayCopNames: true

Layout/CaseIndentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/unit/lib/web/iframe_dsl_spec.rb'

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 150

Style/CaseEquality:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/EvalWithLocation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinGrouping:
  EnforcedStyle: separated
  Exclude:
    - '**/*_steps.rb'
    - 'tmp/**'

Style/MixinUsage:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/TrivialAccessors:
  AllowDSLWriters: true

Style/YodaCondition:
  Enabled: false
