# See full list of defaults here: https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# To see all cops used see here: https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml

LineLength:
  Max: 120

Style/CaseIndentation:
  Enabled: false

Style/EmptyElse:
  Enabled: false