source 'https://rubygems.org'

gem 'howitzer' #, github: "strongqa/howitzer", branch: "develop"
gem 'minitest', '~>4.0' # limitation for cucumber (1.2.5)
gem 'minitest-reporters', '>= 0.5.0' # is necessary in RubyMine with minitest (4.7.5)
gem 'debase'         # are necessary for debugging
gem 'ruby-debug-ide' # in RubyMine