name: "Lint Pull Request"

permissions:
  id-token: write
  contents: read
  checks: write
  actions: write
  statuses: write
  pull-requests: write
  issues: write

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            fix
            feat
            build
            chore
            ci
            docs
            style
            refactor
            perf
            test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
