name: Howitzer

on:
  pull_request:
    branches: master 

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - 2.6.10 
          - 2.7.6
          - 3.0.4
          - 3.1.2

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run rubocop
        run: bundle exec rake rubocop
      - name: Run yard:validate
        run: bundle exec rake yard:validate
      - name: Run spec
        run: bundle exec rake spec
      - name: Run cucumber
        run: bundle exec rake cucumber