###########################################################
#  COMMON SETTINGS                                        #
###########################################################
 debug_mode: false

###########################################################
# APPLICATION SETTINGS                                    #
###########################################################
 app_host: my.website.com
 app_url: "http://${app_host}"
 def_test_user: test@test.com
 def_test_pass: mypass
 def_test_name: Auto Tester

###########################################################
# TEST ENVIRONMENTS SETTINGS                              #
###########################################################

 # Specify one of the following drivers: selenium, selenium_dev, webkit, sauce
 driver: webkit

 # -Selenium-
 # specify one of next browsers: iexplore (ie), firefox (ff), chrome, opera
 sel_browser: ff
 sel_firefox_version: 10
 sel_firebug_version: 1.9.1
 sel_firepath_version: 0.9.7

 # -SauceLabs-
 sl_user: some_user
 sl_api_key: some_api_key
 sl_url: "http://${sl_user}:${sl_api_key}@ondemand.saucelabs.com:80/wd/hub"
 sl_platform: :VISTA
 sl_browser_name: firefox
 sl_selenium_version: "2.18.0"
 sl_max_duration: '1800'
 sl_idle_timeout: '180'

###########################################################
# DATABASE SETTINGS                                       #
###########################################################



###########################################################
# LOGGER SETTINGS                                         #
###########################################################
 log_dir: "log"
 txt_log: log.txt
 selenium_server_log: selenium-server.log
 required_clean_logs: true

###########################################################
# MAIL SETTINGS                                           #
###########################################################
 mail_smtp_server: smtp.demo.com
 mail_smtp_port: 25
 mail_smtp_domain: demo.com
 mail_smtp_user_name: test_user
 mail_smtp_user_pass: mypass

 mail_pop3_server: pop.demo.com
 mail_pop3_port: 995
 mail_pop3_timeout: 120
 mail_pop3_domain: ${mail_smtp_domain}
 mail_pop3_user_name: test_user
 mail_pop3_user_pass: mypass

############################################################
# TIMEOUTS                                                 #
############################################################
 timeout_tiny: 1
 timeout_short: 3
 timeout_small: 20
 timeout_medium: 60

